/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductSpecs = IDL.Record({
  'ram' : IDL.Nat,
  'storage' : IDL.Nat,
  'display' : IDL.Text,
  'processor' : IDL.Text,
});
export const ProductCategory = IDL.Variant({
  'gaming' : IDL.Null,
  'business' : IDL.Null,
  'student' : IDL.Null,
  'general' : IDL.Null,
});
export const ProductInput = IDL.Record({
  'stockQuantity' : IDL.Nat,
  'featured' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'specs' : ProductSpecs,
  'imageUrl' : IDL.Text,
  'category' : ProductCategory,
  'brand' : IDL.Text,
  'price' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ServiceType = IDL.Variant({
  'repair' : IDL.Null,
  'demo' : IDL.Null,
  'consultation' : IDL.Null,
});
export const Time = IDL.Int;
export const BookingInput = IDL.Record({
  'customerName' : IDL.Text,
  'serviceType' : ServiceType,
  'productId' : IDL.Opt(IDL.Nat),
  'email' : IDL.Text,
  'preferredTimeSlot' : IDL.Text,
  'preferredDate' : Time,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const ProductUpdate = IDL.Record({
  'stockQuantity' : IDL.Opt(IDL.Nat),
  'featured' : IDL.Opt(IDL.Bool),
  'name' : IDL.Opt(IDL.Text),
  'description' : IDL.Opt(IDL.Text),
  'specs' : IDL.Opt(ProductSpecs),
  'imageUrl' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(ProductCategory),
  'brand' : IDL.Opt(IDL.Text),
  'price' : IDL.Opt(IDL.Nat),
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'stockQuantity' : IDL.Nat,
  'featured' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'specs' : ProductSpecs,
  'imageUrl' : IDL.Text,
  'category' : ProductCategory,
  'brand' : IDL.Text,
  'price' : IDL.Nat,
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : BookingStatus,
  'serviceType' : ServiceType,
  'productId' : IDL.Opt(IDL.Nat),
  'email' : IDL.Text,
  'preferredTimeSlot' : IDL.Text,
  'preferredDate' : Time,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CartItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const BookingUpdate = IDL.Record({
  'status' : IDL.Opt(BookingStatus),
  'notes' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func([ProductInput], [IDL.Nat], []),
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([], [IDL.Bool], []),
  'confirmBooking' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'createBooking' : IDL.Func([BookingInput], [IDL.Nat], []),
  'editProduct' : IDL.Func([IDL.Nat, ProductUpdate], [IDL.Bool], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAvailableTimeSlots' : IDL.Func([Time], [IDL.Vec(IDL.Text)], ['query']),
  'getBooking' : IDL.Func([IDL.Nat], [IDL.Opt(Booking)], ['query']),
  'getBookingsByEmail' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProductsByCategory' : IDL.Func(
      [ProductCategory],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeFromCart' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'removeProduct' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchProductsByName' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'updateBooking' : IDL.Func([IDL.Nat, BookingUpdate], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductSpecs = IDL.Record({
    'ram' : IDL.Nat,
    'storage' : IDL.Nat,
    'display' : IDL.Text,
    'processor' : IDL.Text,
  });
  const ProductCategory = IDL.Variant({
    'gaming' : IDL.Null,
    'business' : IDL.Null,
    'student' : IDL.Null,
    'general' : IDL.Null,
  });
  const ProductInput = IDL.Record({
    'stockQuantity' : IDL.Nat,
    'featured' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'specs' : ProductSpecs,
    'imageUrl' : IDL.Text,
    'category' : ProductCategory,
    'brand' : IDL.Text,
    'price' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ServiceType = IDL.Variant({
    'repair' : IDL.Null,
    'demo' : IDL.Null,
    'consultation' : IDL.Null,
  });
  const Time = IDL.Int;
  const BookingInput = IDL.Record({
    'customerName' : IDL.Text,
    'serviceType' : ServiceType,
    'productId' : IDL.Opt(IDL.Nat),
    'email' : IDL.Text,
    'preferredTimeSlot' : IDL.Text,
    'preferredDate' : Time,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ProductUpdate = IDL.Record({
    'stockQuantity' : IDL.Opt(IDL.Nat),
    'featured' : IDL.Opt(IDL.Bool),
    'name' : IDL.Opt(IDL.Text),
    'description' : IDL.Opt(IDL.Text),
    'specs' : IDL.Opt(ProductSpecs),
    'imageUrl' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(ProductCategory),
    'brand' : IDL.Opt(IDL.Text),
    'price' : IDL.Opt(IDL.Nat),
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'stockQuantity' : IDL.Nat,
    'featured' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'specs' : ProductSpecs,
    'imageUrl' : IDL.Text,
    'category' : ProductCategory,
    'brand' : IDL.Text,
    'price' : IDL.Nat,
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : BookingStatus,
    'serviceType' : ServiceType,
    'productId' : IDL.Opt(IDL.Nat),
    'email' : IDL.Text,
    'preferredTimeSlot' : IDL.Text,
    'preferredDate' : Time,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CartItem = IDL.Record({ 'productId' : IDL.Nat, 'quantity' : IDL.Nat });
  const BookingUpdate = IDL.Record({
    'status' : IDL.Opt(BookingStatus),
    'notes' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func([ProductInput], [IDL.Nat], []),
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([], [IDL.Bool], []),
    'confirmBooking' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'createBooking' : IDL.Func([BookingInput], [IDL.Nat], []),
    'editProduct' : IDL.Func([IDL.Nat, ProductUpdate], [IDL.Bool], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAvailableTimeSlots' : IDL.Func([Time], [IDL.Vec(IDL.Text)], ['query']),
    'getBooking' : IDL.Func([IDL.Nat], [IDL.Opt(Booking)], ['query']),
    'getBookingsByEmail' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [ProductCategory],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeFromCart' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'removeProduct' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchProductsByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'updateBooking' : IDL.Func([IDL.Nat, BookingUpdate], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };