/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'customerName' : string,
  'status' : BookingStatus,
  'serviceType' : ServiceType,
  'productId' : [] | [bigint],
  'email' : string,
  'preferredTimeSlot' : string,
  'preferredDate' : Time,
  'notes' : string,
  'phone' : string,
}
export interface BookingInput {
  'customerName' : string,
  'serviceType' : ServiceType,
  'productId' : [] | [bigint],
  'email' : string,
  'preferredTimeSlot' : string,
  'preferredDate' : Time,
  'notes' : string,
  'phone' : string,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'confirmed' : null };
export interface BookingUpdate {
  'status' : [] | [BookingStatus],
  'notes' : [] | [string],
}
export interface CartItem { 'productId' : bigint, 'quantity' : bigint }
export interface Product {
  'id' : bigint,
  'stockQuantity' : bigint,
  'featured' : boolean,
  'name' : string,
  'description' : string,
  'specs' : ProductSpecs,
  'imageUrl' : string,
  'category' : ProductCategory,
  'brand' : string,
  'price' : bigint,
}
export type ProductCategory = { 'gaming' : null } |
  { 'business' : null } |
  { 'student' : null } |
  { 'general' : null };
export interface ProductInput {
  'stockQuantity' : bigint,
  'featured' : boolean,
  'name' : string,
  'description' : string,
  'specs' : ProductSpecs,
  'imageUrl' : string,
  'category' : ProductCategory,
  'brand' : string,
  'price' : bigint,
}
export interface ProductSpecs {
  'ram' : bigint,
  'storage' : bigint,
  'display' : string,
  'processor' : string,
}
export interface ProductUpdate {
  'stockQuantity' : [] | [bigint],
  'featured' : [] | [boolean],
  'name' : [] | [string],
  'description' : [] | [string],
  'specs' : [] | [ProductSpecs],
  'imageUrl' : [] | [string],
  'category' : [] | [ProductCategory],
  'brand' : [] | [string],
  'price' : [] | [bigint],
}
export type ServiceType = { 'repair' : null } |
  { 'demo' : null } |
  { 'consultation' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[ProductInput], bigint>,
  'addToCart' : ActorMethod<[bigint, bigint], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], boolean>,
  'confirmBooking' : ActorMethod<[bigint], boolean>,
  'createBooking' : ActorMethod<[BookingInput], bigint>,
  'editProduct' : ActorMethod<[bigint, ProductUpdate], boolean>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAvailableTimeSlots' : ActorMethod<[Time], Array<string>>,
  'getBooking' : ActorMethod<[bigint], [] | [Booking]>,
  'getBookingsByEmail' : ActorMethod<[string], Array<Booking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProductsByCategory' : ActorMethod<[ProductCategory], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeFromCart' : ActorMethod<[bigint], boolean>,
  'removeProduct' : ActorMethod<[bigint], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProductsByName' : ActorMethod<[string], Array<Product>>,
  'updateBooking' : ActorMethod<[bigint, BookingUpdate], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];