/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ProductInput {
    stockQuantity: bigint;
    featured: boolean;
    name: string;
    description: string;
    specs: ProductSpecs;
    imageUrl: string;
    category: ProductCategory;
    brand: string;
    price: bigint;
}
export type Time = bigint;
export interface ProductUpdate {
    stockQuantity?: bigint;
    featured?: boolean;
    name?: string;
    description?: string;
    specs?: ProductSpecs;
    imageUrl?: string;
    category?: ProductCategory;
    brand?: string;
    price?: bigint;
}
export interface BookingInput {
    customerName: string;
    serviceType: ServiceType;
    productId?: bigint;
    email: string;
    preferredTimeSlot: string;
    preferredDate: Time;
    notes: string;
    phone: string;
}
export interface BookingUpdate {
    status?: BookingStatus;
    notes?: string;
}
export interface ProductSpecs {
    ram: bigint;
    storage: bigint;
    display: string;
    processor: string;
}
export interface Booking {
    id: bigint;
    customerName: string;
    status: BookingStatus;
    serviceType: ServiceType;
    productId?: bigint;
    email: string;
    preferredTimeSlot: string;
    preferredDate: Time;
    notes: string;
    phone: string;
}
export interface CartItem {
    productId: bigint;
    quantity: bigint;
}
export interface Product {
    id: bigint;
    stockQuantity: bigint;
    featured: boolean;
    name: string;
    description: string;
    specs: ProductSpecs;
    imageUrl: string;
    category: ProductCategory;
    brand: string;
    price: bigint;
}
export interface UserProfile {
    name: string;
}
export enum BookingStatus {
    cancelled = "cancelled",
    pending = "pending",
    confirmed = "confirmed"
}
export enum ProductCategory {
    gaming = "gaming",
    business = "business",
    student = "student",
    general = "general"
}
export enum ServiceType {
    repair = "repair",
    demo = "demo",
    consultation = "consultation"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addProduct(input: ProductInput): Promise<bigint>;
    addToCart(productId: bigint, quantity: bigint): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearCart(): Promise<boolean>;
    confirmBooking(bookingId: bigint): Promise<boolean>;
    createBooking(input: BookingInput): Promise<bigint>;
    editProduct(productId: bigint, update: ProductUpdate): Promise<boolean>;
    getAllProducts(): Promise<Array<Product>>;
    getAvailableTimeSlots(_date: Time): Promise<Array<string>>;
    getBooking(bookingId: bigint): Promise<Booking | null>;
    getBookingsByEmail(email: string): Promise<Array<Booking>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCart(): Promise<Array<CartItem>>;
    getProduct(productId: bigint): Promise<Product | null>;
    getProductsByCategory(category: ProductCategory): Promise<Array<Product>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    removeFromCart(productId: bigint): Promise<boolean>;
    removeProduct(productId: bigint): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchProductsByName(searchTerm: string): Promise<Array<Product>>;
    updateBooking(bookingId: bigint, update: BookingUpdate): Promise<boolean>;
}
import type { Booking as _Booking, BookingInput as _BookingInput, BookingStatus as _BookingStatus, BookingUpdate as _BookingUpdate, Product as _Product, ProductCategory as _ProductCategory, ProductInput as _ProductInput, ProductSpecs as _ProductSpecs, ProductUpdate as _ProductUpdate, ServiceType as _ServiceType, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addProduct(arg0: ProductInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(to_candid_ProductInput_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(to_candid_ProductInput_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addToCart(arg0: bigint, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addToCart(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToCart(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearCart(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.clearCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearCart();
            return result;
        }
    }
    async confirmBooking(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmBooking(arg0);
            return result;
        }
    }
    async createBooking(arg0: BookingInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(to_candid_BookingInput_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(to_candid_BookingInput_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async editProduct(arg0: bigint, arg1: ProductUpdate): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.editProduct(arg0, to_candid_ProductUpdate_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editProduct(arg0, to_candid_ProductUpdate_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableTimeSlots(arg0: Time): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableTimeSlots(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableTimeSlots(arg0);
            return result;
        }
    }
    async getBooking(arg0: bigint): Promise<Booking | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooking(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooking(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsByEmail(arg0: string): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByEmail(arg0);
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByEmail(arg0);
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCart(): Promise<Array<CartItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCart();
            return result;
        }
    }
    async getProduct(arg0: bigint): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductsByCategory(arg0: ProductCategory): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsByCategory(to_candid_ProductCategory_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsByCategory(to_candid_ProductCategory_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async removeFromCart(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromCart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromCart(arg0);
            return result;
        }
    }
    async removeProduct(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeProduct(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchProductsByName(arg0: string): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchProductsByName(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchProductsByName(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateBooking(arg0: bigint, arg1: BookingUpdate): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBooking(arg0, to_candid_BookingUpdate_n31(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBooking(arg0, to_candid_BookingUpdate_n31(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_BookingStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_ProductCategory_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductCategory): ProductCategory {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceType_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceType): ServiceType {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Booking]): Booking | null {
    return value.length === 0 ? null : from_candid_Booking_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : from_candid_Product_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    stockQuantity: bigint;
    featured: boolean;
    name: string;
    description: string;
    specs: _ProductSpecs;
    imageUrl: string;
    category: _ProductCategory;
    brand: string;
    price: bigint;
}): {
    id: bigint;
    stockQuantity: bigint;
    featured: boolean;
    name: string;
    description: string;
    specs: ProductSpecs;
    imageUrl: string;
    category: ProductCategory;
    brand: string;
    price: bigint;
} {
    return {
        id: value.id,
        stockQuantity: value.stockQuantity,
        featured: value.featured,
        name: value.name,
        description: value.description,
        specs: value.specs,
        imageUrl: value.imageUrl,
        category: from_candid_ProductCategory_n16(_uploadFile, _downloadFile, value.category),
        brand: value.brand,
        price: value.price
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerName: string;
    status: _BookingStatus;
    serviceType: _ServiceType;
    productId: [] | [bigint];
    email: string;
    preferredTimeSlot: string;
    preferredDate: _Time;
    notes: string;
    phone: string;
}): {
    id: bigint;
    customerName: string;
    status: BookingStatus;
    serviceType: ServiceType;
    productId?: bigint;
    email: string;
    preferredTimeSlot: string;
    preferredDate: Time;
    notes: string;
    phone: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_BookingStatus_n21(_uploadFile, _downloadFile, value.status),
        serviceType: from_candid_ServiceType_n23(_uploadFile, _downloadFile, value.serviceType),
        productId: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.productId)),
        email: value.email,
        preferredTimeSlot: value.preferredTimeSlot,
        preferredDate: value.preferredDate,
        notes: value.notes,
        phone: value.phone
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gaming: null;
} | {
    business: null;
} | {
    student: null;
} | {
    general: null;
}): ProductCategory {
    return "gaming" in value ? ProductCategory.gaming : "business" in value ? ProductCategory.business : "student" in value ? ProductCategory.student : "general" in value ? ProductCategory.general : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    confirmed: null;
}): BookingStatus {
    return "cancelled" in value ? BookingStatus.cancelled : "pending" in value ? BookingStatus.pending : "confirmed" in value ? BookingStatus.confirmed : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    repair: null;
} | {
    demo: null;
} | {
    consultation: null;
}): ServiceType {
    return "repair" in value ? ServiceType.repair : "demo" in value ? ServiceType.demo : "consultation" in value ? ServiceType.consultation : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n19(_uploadFile, _downloadFile, x));
}
function to_candid_BookingInput_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingInput): _BookingInput {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_BookingStatus_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function to_candid_BookingUpdate_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingUpdate): _BookingUpdate {
    return to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid_ProductCategory_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCategory): _ProductCategory {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_ProductInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductInput): _ProductInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_ProductUpdate_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductUpdate): _ProductUpdate {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): _ServiceType {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stockQuantity?: bigint;
    featured?: boolean;
    name?: string;
    description?: string;
    specs?: ProductSpecs;
    imageUrl?: string;
    category?: ProductCategory;
    brand?: string;
    price?: bigint;
}): {
    stockQuantity: [] | [bigint];
    featured: [] | [boolean];
    name: [] | [string];
    description: [] | [string];
    specs: [] | [_ProductSpecs];
    imageUrl: [] | [string];
    category: [] | [_ProductCategory];
    brand: [] | [string];
    price: [] | [bigint];
} {
    return {
        stockQuantity: value.stockQuantity ? candid_some(value.stockQuantity) : candid_none(),
        featured: value.featured ? candid_some(value.featured) : candid_none(),
        name: value.name ? candid_some(value.name) : candid_none(),
        description: value.description ? candid_some(value.description) : candid_none(),
        specs: value.specs ? candid_some(value.specs) : candid_none(),
        imageUrl: value.imageUrl ? candid_some(value.imageUrl) : candid_none(),
        category: value.category ? candid_some(to_candid_ProductCategory_n3(_uploadFile, _downloadFile, value.category)) : candid_none(),
        brand: value.brand ? candid_some(value.brand) : candid_none(),
        price: value.price ? candid_some(value.price) : candid_none()
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stockQuantity: bigint;
    featured: boolean;
    name: string;
    description: string;
    specs: ProductSpecs;
    imageUrl: string;
    category: ProductCategory;
    brand: string;
    price: bigint;
}): {
    stockQuantity: bigint;
    featured: boolean;
    name: string;
    description: string;
    specs: _ProductSpecs;
    imageUrl: string;
    category: _ProductCategory;
    brand: string;
    price: bigint;
} {
    return {
        stockQuantity: value.stockQuantity,
        featured: value.featured,
        name: value.name,
        description: value.description,
        specs: value.specs,
        imageUrl: value.imageUrl,
        category: to_candid_ProductCategory_n3(_uploadFile, _downloadFile, value.category),
        brand: value.brand,
        price: value.price
    };
}
function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: BookingStatus;
    notes?: string;
}): {
    status: [] | [_BookingStatus];
    notes: [] | [string];
} {
    return {
        status: value.status ? candid_some(to_candid_BookingStatus_n33(_uploadFile, _downloadFile, value.status)) : candid_none(),
        notes: value.notes ? candid_some(value.notes) : candid_none()
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    serviceType: ServiceType;
    productId?: bigint;
    email: string;
    preferredTimeSlot: string;
    preferredDate: Time;
    notes: string;
    phone: string;
}): {
    customerName: string;
    serviceType: _ServiceType;
    productId: [] | [bigint];
    email: string;
    preferredTimeSlot: string;
    preferredDate: _Time;
    notes: string;
    phone: string;
} {
    return {
        customerName: value.customerName,
        serviceType: to_candid_ServiceType_n9(_uploadFile, _downloadFile, value.serviceType),
        productId: value.productId ? candid_some(value.productId) : candid_none(),
        email: value.email,
        preferredTimeSlot: value.preferredTimeSlot,
        preferredDate: value.preferredDate,
        notes: value.notes,
        phone: value.phone
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): {
    repair: null;
} | {
    demo: null;
} | {
    consultation: null;
} {
    return value == ServiceType.repair ? {
        repair: null
    } : value == ServiceType.demo ? {
        demo: null
    } : value == ServiceType.consultation ? {
        consultation: null
    } : value;
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    confirmed: null;
} {
    return value == BookingStatus.cancelled ? {
        cancelled: null
    } : value == BookingStatus.pending ? {
        pending: null
    } : value == BookingStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCategory): {
    gaming: null;
} | {
    business: null;
} | {
    student: null;
} | {
    general: null;
} {
    return value == ProductCategory.gaming ? {
        gaming: null
    } : value == ProductCategory.business ? {
        business: null
    } : value == ProductCategory.student ? {
        student: null
    } : value == ProductCategory.general ? {
        general: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
